# Generated by Django 4.2.5 on 2023-10-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('1', 'Customer'), ('2', 'Editor'), ('3', 'Vendor')], default=1, max_length=20),
        ),
    ]
