# Generated by Django 4.2.5 on 2023-09-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='slug',
        ),
    ]
