# Generated by Django 4.2.4 on 2023-09-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_slug'),
        ('home', '0003_displayhotproductincategories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('created_at', models.DateTimeField()),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.categories')),
            ],
        ),
    ]
