# Generated by Django 4.2.5 on 2023-10-27 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorstore',
            name='slug',
            field=models.CharField(max_length=115, unique=True),
        ),
    ]
