# Generated by Django 4.2.5 on 2023-11-06 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor_stores',
        ),
    ]
