# Generated by Django 4.2.5 on 2023-09-20 13:50

from django.db import migrations
from django.utils.text import slugify

def copy_data(apps, schema_editor):
    HomeIndustry = apps.get_model('home', 'Industry')
    ProductsIndustry = apps.get_model('products', 'Industry')
    HomeCategories = apps.get_model('home', 'Categories')
    ProductsCategories = apps.get_model('products', 'Categories')
    HomeSubCategories = apps.get_model('home', 'SubCategories')
    ProductsSubCategories = apps.get_model('products', 'SubCategories')

    for industry in HomeIndustry.objects.all():
        ProductsIndustry.objects.create(
            name=industry.name,
            slug=slugify(industry.name),
            created_at=industry.created_at,
        )

    for category in HomeCategories.objects.all():
        ProductsCategories.objects.create(
            name=category.name,
            slug=slugify(category.name),
            industry_id=category.industry_id,
            created_at=category.created_at,
        )

    for subcategory in HomeSubCategories.objects.all():
        ProductsSubCategories.objects.create(
            name=subcategory.name,
            slug=slugify(subcategory.name),
            categories_id=subcategory.categories_id,
            created_at=subcategory.created_at,
        )



class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]
