# Generated by Django 4.2.5 on 2023-09-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_cart_cupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedeoderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
