# Generated by Django 4.2.5 on 2023-09-20 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230920_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('regular_price', models.PositiveIntegerField()),
                ('discounted_price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('modle', models.CharField(max_length=50)),
                ('tag', models.CharField(help_text='enter your tag coma separated', max_length=50)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.categories')),
            ],
        ),
    ]
