# Generated by Django 4.2.5 on 2023-11-06 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '__first__'),
        ('products', '0002_remove_product_vendor_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_stores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vendors.vendorstore'),
        ),
    ]
