# Generated by Django 4.2.5 on 2023-09-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creayed_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
