# Generated by Django 4.2.5 on 2023-09-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_placedeoderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedoder',
            name='status',
            field=models.CharField(choices=[('Oder Recived', 'Oder Recived'), ('Oder Packed', 'Oder Packed'), ('Oder OnTheWay', 'Oder OnTheWay'), ('Oder Shipped', 'Oder Shipped')], default='Oder Recived', max_length=50),
        ),
    ]
