# Generated by Django 4.2.5 on 2023-10-01 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_placedoder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedeoderitem',
            name='placed_oder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.placedoder'),
        ),
    ]
