# Generated by Django 4.2.5 on 2023-09-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_creayed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creayed_at',
            new_name='created_at',
        ),
    ]
