# Generated by Django 4.2.5 on 2023-11-18 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productstarratingandreview_review_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstarratingandreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
