# Generated by Django 4.2.5 on 2023-10-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_placedoder_order_number_completedoderitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedoder',
            name='oder_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placedoder',
            name='order_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
