# Generated by Django 4.2.5 on 2023-10-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_completedoder_oder_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedoder',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.customeraddress'),
        ),
    ]
