# Generated by Django 4.2.5 on 2023-10-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_placedoder_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedoder',
            name='sample',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.customeraddress'),
        ),
        migrations.AlterField(
            model_name='placedoder',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipping_address', to='products.customeraddress'),
        ),
    ]
