# Generated by Django 4.2.5 on 2023-10-11 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_placedoder_sample_alter_placedoder_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedoderitems',
            name='completed_oder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_items', to='products.completedoder'),
        ),
    ]
