# Generated by Django 4.2.5 on 2023-10-20 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_alter_completedoderitems_completed_oder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_with_product_in_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placedeoderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='placedeoderitem',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
