# Generated by Django 4.2.5 on 2023-10-20 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_cart_user_alter_placedeoderitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedoder',
            name='sample',
        ),
        migrations.AlterField(
            model_name='placedeoderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='placedoder',
            name='sub_total_price',
            field=models.FloatField(default=None),
        ),
    ]
