# Generated by Django 4.2.5 on 2023-09-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='discounted_parcent',
        ),
    ]
