# Generated by Django 4.2.5 on 2023-10-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_placedoder_sample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedoder',
            name='sub_total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
