# Generated by Django 4.2.5 on 2023-09-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='mobile',
            field=models.PositiveIntegerField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
