# Generated by Django 4.2.5 on 2023-09-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_customeraddress_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='is_shipping',
            field=models.BooleanField(default=True),
        ),
    ]
