# Generated by Django 4.2.5 on 2023-09-28 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_placedoder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedoder',
            name='product',
        ),
        migrations.AlterField(
            model_name='placedoder',
            name='placed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PlacedeOderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('placed_oder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.placedoder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
